### ISSUE TITLE
Multiple symlinked copies of JRE are in final docker image

### ISSUE THREAD

**Issue by brentonr** [williamsbdev/minimal-docker-image-maker#1]
The `create_minimal_image.py` script will find binaries in any location under `/usr/lib/jvm`, which includes several symlinked copies of the jre installed.

These copies are created as full files instead of symlinks in the target `Dockerfile-minimal` image via the `build-output` directory.

Because these copies aren't used, instead use only the `/usr/lib/jvm/jre` directory, causing only one copy to be included in `build-output`.

**Comment by williamsbdev** [comment]
@brentonr - Thank you so much for finding this! My initial attempt at this was simply to have a working Java Spring Boot application with only the JRE in it. I did not verify it's size or the contents were only what it needed to be.
